### ISSUE TITLE
Correct library name for drop-in replacement

### ISSUE THREAD

**Issue by huhong789** [bwickman97/ffmalloc#3]
In the `compilation` part of README, the drop-in replacement of glibc is the library with "np". See below

To use ffmalloc as a drop-in replacement for glibc's implementation of malloc, link to either ~~libffmallocmt.so~~ libffmallocnpmt.so to include support for pthreads or ~~libffmallocst.so~~ libffmallocnpst.so if your application is single threaded.

**Comment by bwickman97** [comment]
D'oh! Fixed - thanks
